apiVersion: apps/v1
kind: Deployment
metadata:
  name: indoestate
  labels:
    app: indoestate
  annotations:
    force-update: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indoestate
  template:
    metadata:
      labels:
        app: indoestate
    spec:
      imagePullSecrets:
        - name: swpsrepo
      containers:
        - name: indoestate
          image: registry.digitalocean.com/swpsrepo/indoestate/indoestate:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0          

---
apiVersion: v1
kind: Service
metadata:
  name: indoestate
spec:
  type: LoadBalancer
  selector:
    app: indoestate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
