name: Deploy to NextWallet Server

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
    build:
      runs-on: self-hosted
        
      steps:
        - name: Checking out latest code
          uses: actions/checkout@v3
  
        - name: Build Docker Image
          run: docker build -t registry.digitalocean.com/swpsrepo/indoestate/indoestate:latest .
          

        - name: Push to Registry
          run: docker push registry.digitalocean.com/swpsrepo/indoestate/indoestate:latest
  
        - name: Login and push to Kubernetes
          run: | 
            kubectl apply -f indoestate.yml
            kubectl rollout restart deployment indoestate
      
          
        
        
      
